"""Hausman IV construction and control-function first stage."""

import numpy as np


def hausman_iv(prices, stores, weeks):
    """Mean price of same good across other stores in same week."""

    G = prices.shape[1]
    Z = np.zeros_like(prices)
    for j in range(G):
        for i, (s, wk) in enumerate(zip(stores, weeks)):
            mask = (stores != s) & (weeks == wk)
            Z[i, j] = prices[mask, j].mean() if mask.sum() else prices[:, j].mean()
    return Z


def cf_first_stage(log_p, Z):
    """OLS first stage for the control-function (CF) endogeneity correction.

    For each good j, regresses log(p_j) on [1, Z_j] to obtain fitted values.
    Returns the OLS residuals  v̂_j = log(p_j) − ŷ_j  as additional inputs
    to the neural demand network so that price endogeneity is absorbed.

    At *evaluation* time (counterfactual welfare / elasticities) pass
    v_hat = zeros so the network recovers the structural demand without
    the endogenous component.

    Parameters
    ----------
    log_p : ndarray (N, G)
        Log prices.
    Z     : ndarray (N, G)
        Instruments.  For the Dominick's pipeline these are Hausman mean
        prices across stores; for the simulation pipeline these are the
        cost-shifter vectors Z used to generate prices.

    Returns
    -------
    v_hat : ndarray (N, G)
        First-stage OLS residuals.
    r_sq  : ndarray (G,)
        First-stage R² for each good.
    """
    N, G = log_p.shape
    v_hat = np.zeros((N, G), dtype=np.float64)
    r_sq  = np.zeros(G, dtype=np.float64)
    for j in range(G):
        X_j     = np.column_stack([np.ones(N), Z[:, j]])
        gamma_j = np.linalg.lstsq(X_j, log_p[:, j], rcond=None)[0]
        fitted  = X_j @ gamma_j
        resid   = log_p[:, j] - fitted
        v_hat[:, j] = resid
        ss_tot  = np.sum((log_p[:, j] - log_p[:, j].mean()) ** 2)
        r_sq[j] = 1.0 - np.sum(resid ** 2) / max(ss_tot, 1e-12)
    return v_hat.astype(np.float32), r_sq


def cf_first_stage_full(p, Z, log_transform: bool = False):
    """Control-function first stage using *all* G instruments for each equation.

    Unlike :func:`cf_first_stage`, which regresses p_j only on its own
    instrument Z_j, this version regresses each p_j on the full instrument
    matrix [1, Z_0, …, Z_{G-1}], matching the identification strategy used
    by Logit-IV (BLPLogitIV).  This is more efficient when instruments are
    (cross-good) correlated and is the correct specification when prices are
    generated by an additive DGP such as p_j = Z_j + ν_j + ξ_j.

    Parameters
    ----------
    p             : ndarray (N, G)
        Prices (or log-prices if ``log_transform=True`` is applied upstream).
        Pass raw prices when the DGP is additive in levels (p = Z + shock);
        pass log-prices when the DGP is multiplicative / log-linear.
    Z             : ndarray (N, G)
        Instrument matrix.  All G columns are used for each equation.
    log_transform : bool, default False
        If True, take log(p) before running the first stage.  Useful for
        log-linear DGPs; leave False for additive / levels DGPs.

    Returns
    -------
    v_hat : ndarray (N, G)  float32
        First-stage OLS residuals (p_j − ŷ_j or log(p_j) − ŷ_j).
    r_sq  : ndarray (G,)    float64
        First-stage R² for each equation.
    """
    p = np.asarray(p, dtype=np.float64)
    if log_transform:
        p = np.log(np.maximum(p, 1e-8))

    N, G  = p.shape
    Z_aug = np.column_stack([np.ones(N), Z])   # (N, G+1) — intercept + all Z
    v_hat = np.zeros((N, G), dtype=np.float64)
    r_sq  = np.zeros(G, dtype=np.float64)

    for j in range(G):
        gamma_j = np.linalg.lstsq(Z_aug, p[:, j], rcond=None)[0]
        fitted  = Z_aug @ gamma_j
        resid   = p[:, j] - fitted
        v_hat[:, j] = resid
        ss_tot  = np.sum((p[:, j] - p[:, j].mean()) ** 2)
        r_sq[j] = 1.0 - np.sum(resid ** 2) / max(ss_tot, 1e-12)

    return v_hat.astype(np.float32), r_sq
